### ISSUE TITLE
POI off by 45 degrees

### ISSUE THREAD

**Issue by Djembejo** [Vuframe/PanicAR#35]
Event with the Demo App all POI seem to be off 45˚, I have tested on iPad air with ios 9.2.1 iPhone 6 with ios 9.2.1 iPhone 5s with ios 9.3. 

I am using locations within about a 10 mile radius, I am testing the app using wifi, how accurate should the POI be ? 

Is there a setting for accuracy or is there something I am missing ?

**Comment by azeitler** [comment]
this is due to the compass not being properly calibrated. try doing the "compass shuffle" (https://www.youtube.com/watch?v=rkHcxsdeJrw) then it should snap into the right postion. a reboot of the device might also help. Please note: Wifi-only devices have VERY low accuracy (+/- 50 meters) in the location signal. This might also be the cause.
